version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/*

#version: 0.2
#
#phases:
#  install:
#    runtime-versions:
#      java: corretto17
#  pre_build:
#    commands:
#      - echo Logging in to Amazon ECR...
#      - echo $AWS_DEFAULT_REGION
#      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
#      - echo $REPOSITORY_URI
#      - aws --version
#      - aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email
#      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
#      - REPOSITORY_URI=421732516831.dkr.ecr.us-east-1.amazonaws.com/stockinfa
#      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
#      - IMAGE_TAG=${COMMIT_HASH:=latest}
#  build:
#    commands:
#      - echo Build started on `date`
#      - mvn install
#      - echo Building the Docker image...
#      - docker build -t $REPOSITORY_URI:latest .
#      - echo Tagging Docker image...
#      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
#  post_build:
#    commands:
#      - echo Build completed on `date`
#      - echo Pushing the Docker images...
#      - docker push $REPOSITORY_URI:$IMAGE_TAG
#artifacts:
#  files:
#    - target/stockinfo.jar