apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockinfo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: stockinfo-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stockinfo-deployment
    spec:
      containers:
        - name: stockinfo-deployment
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_password
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: hostname-config
                  key: postgres_host
          image: 421732516831.dkr.ecr.us-east-1.amazonaws.com/stockinfo:latest
          ports:
            - containerPort: 8080