apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: stock-info-app
  region: us-east-1
  version: "1.27"
managedNodeGroups:
  - name: nodeG
    instanceType: t2.small
    minSize: 1
    maxSize: 1
iam:
  withOIDC: true