apiVersion: v1
kind: Service
metadata:
  name: stockinfo-service
  labels:
    app: stockinfo-service
spec:
  selector:
    app: stockinfo-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080