#logging:
#  level:
#    org:
#      springframework:
#        r2dbc: DEBUG

aspect:
  enabled: true

rds:
  db:
    url: testrds.cdhhic49lpmm.us-east-1.rds.amazonaws.com/stockdb?sslMode=require
    username: postgres
    password: postgres

local:
  db:
    url: localhost:5432/stocks-db
    username: postgres
    password: postgres

spring:
  codec:
    max-in-memory-size: 10MB
  r2dbc:
    url: r2dbc:postgresql://${rds.db.url}
    username: ${rds.db.username}
    password: ${rds.db.password}
    pool:
      enabled: true
      initial-size: 50
      max-size: 100
  flyway:
    url: jdbc:postgresql://${rds.db.url}
    locations: classpath:db/migration
    user: ${rds.db.username}
    password: ${rds.db.password}
    baseline-on-migrate: true

api:
  external:
    ref-data-url: https://api.iex.cloud/v1/data/CORE/REF_DATA?token=%s
    stock-data-url: https://api.iex.cloud/v1/data/core/quote/%s?token=%s
    token: pk_36fe63649f1c441abc528f05f6f2ea6d

service:
  number-of-companies: 200
