#logging:
#  level:
#    org:
#      springframework:
#        r2dbc: DEBUG

aspect:
  enabled: true

spring:
  codec:
    max-in-memory-size: 10MB
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/stocks-db
    username: postgres
    password: postgres

api:
  external:
    ref-data-url: https://api.iex.cloud/v1/data/CORE/REF_DATA?token=%s
    stock-data-url: https://api.iex.cloud/v1/data/core/quote/%s?token=%s
    token: pk_0b2ae7889e7e4d9ca682e041765800e0
  database:
    host: localhost
    port: 5432
    name: stocks-db
    username: postgres
    password: postgres

service:
  number-of-companies: 200
