#logging:
#  level:
#    org:
#      springframework:
#        r2dbc: DEBUG

aspect:
  enabled: true

rds:
  db:
    url: stocks-db.cdhhic49lpmm.us-east-1.rds.amazonaws.com/postgres
    username: postgres
    password: postgres

local:
  db:
    url: localhost:5432/stocks-db
    username: postgres
    password: postgres

spring:
  codec:
    max-in-memory-size: 10MB
  r2dbc:
    url: r2dbc:postgresql://${rds.db.url}
    username: ${rds.db.username}
    password: ${rds.db.password}
  flyway:
    url: jdbc:postgresql://${rds.db.url}
    locations: classpath:db/migration
    user: ${rds.db.username}
    password: ${rds.db.password}
    baseline-on-migrate: true

api:
  external:
    ref-data-url: https://api.iex.cloud/v1/data/CORE/REF_DATA?token=%s
    stock-data-url: https://api.iex.cloud/v1/data/core/quote/%s?token=%s
    token: pk_0b2ae7889e7e4d9ca682e041765800e0
  database:
    host: localhost
    port: 5432
    name: stocks-db
    username: postgres
    password: postgres

service:
  number-of-companies: 200
